// <auto-generated />
using Energy_Insights.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Energy_Insights.Migrations
{
    [DbContext(typeof(Energy_InsightsContext))]
    [Migration("20240426014028_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Energy_Insights.Models.CountryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CountryModel");
                });

            modelBuilder.Entity("Energy_Insights.Models.EnergyGenerationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<int>("EnergyTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("EnergyTypeId");

                    b.ToTable("EnergyGenerationModel");
                });

            modelBuilder.Entity("Energy_Insights.Models.EnergyTypeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EnergyTypeModel");
                });

            modelBuilder.Entity("Energy_Insights.Models.EnergyGenerationModel", b =>
                {
                    b.HasOne("Energy_Insights.Models.CountryModel", "Country")
                        .WithMany("EnergyGenerations")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Energy_Insights.Models.EnergyTypeModel", "EnergyType")
                        .WithMany("EnergyGenerations")
                        .HasForeignKey("EnergyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("EnergyType");
                });

            modelBuilder.Entity("Energy_Insights.Models.CountryModel", b =>
                {
                    b.Navigation("EnergyGenerations");
                });

            modelBuilder.Entity("Energy_Insights.Models.EnergyTypeModel", b =>
                {
                    b.Navigation("EnergyGenerations");
                });
#pragma warning restore 612, 618
        }
    }
}
